services:

  damplab-ui:
    image: hicsail/damplab-ui:main
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - damplab-backend
      - keycloak

  damplab-backend:
    image: hicsail/damplab-backend:main
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://backend-db:27017/damplab
      - JWKS_ENDPOINT=${JWKS_ENDPOINT}
    restart: unless-stopped
    depends_on:
      - backend-db

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    mem_limit: 1gb # of t2.small's 2gb
    ports:
      - 8443:8443
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KC_HTTPS_CERTIFICATE_FILE=/run/secrets/tls-cert-fullchain
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/run/secrets/tls-key
      - KC_HOSTNAME=https://damplab-keycloak.sail.codes
    secrets:
      - tls-cert-fullchain
      - tls-key
    command: start
    restart: unless-stopped
    depends_on:
      - keycloak-db

  backend-db:
    image: mongo:7.0
    volumes:
      - damplab-mongo:/data/db
    restart: unless-stopped

  keycloak-db:
    image: postgres:17
    environment:
      # In prod, should probably create a keycloak db user that is not the db superuser.
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - damplab-keycloak-pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backup:
    image: offen/docker-volume-backup:v2.43.3
    environment:
      BACKUP_CRON_EXPRESSION: "5 2 * * 3"
      AWS_S3_BUCKET_NAME: sail-data-backups
      AWS_S3_PATH: damplab-auth-staging
      AWS_ACCESS_KEY_ID: ${BACKUP_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${BACKUP_AWS_SECRET_ACCESS_KEY}
    # NB: Currently only backing up Keycloak data, not backend data
    volumes:
      - damplab-keycloak-pgdata:/backup:ro
    restart: unless-stopped

volumes:
  damplab-mongo:
    external: true
  damplab-keycloak-pgdata:
    external: true

secrets:
  tls-cert-fullchain:
    file: ./tls/fullchain17.pem
  tls-key:
    file: ./tls/privkey17.pem
