name: PR Checks

on:
  push:
    branches: [ main ]


jobs:
  lint:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 17

    - name: NPM Install
      run: npm-install --only-dev

    - name: Check for Linting Issues
      run: npm run lint

  format:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 17

    - name: NPM Install
      run: npm-install

    - name: Check for Formatting Issues
      run: npm run format

  unit-tests:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 17

    - name: NPM Install
      run: npm-install

    - name: Run Unit Tests
      run: npm run test

  e2e-tests:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 17

    - name: NPM Install
      run: npm-install

    - name: Run E2E Tests
      run: npm run test:e2e

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Docker Build
        uses: docker/build-push-action@v3
        with:
          push: false
